name: Setup
description: Setup Node.js and install dependencies

inputs:
  github_token:
    description: 'GitHub Token'
    required: false
  download_skia:
    description: 'Download Skia Binary Artifacts'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Cache dependencies
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash

    - name: Download Skia Binary Artifacts
      if: ${{ inputs.download_skia == 'true' }}
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: "build-skia.yml"
        repo: shopify/react-native-skia
        path: packages/skia/artifacts
        branch: main

    - name: Copy Artifacts to libs folder
      if: ${{ inputs.download_skia == 'true' }}
      working-directory: packages/skia
      run: yarn workflow-copy-libs
      shell: bash

    - name: Copy Skia Headers
      if: ${{ inputs.download_skia == 'true' }}
      working-directory: packages/skia
      run: yarn copy-skia-headers
      shell: bash
