name: Setup
description: Setup Node.js and install dependencies

inputs:
  github_token:
    description: 'GitHub Token'
    required: false
  download_skia:
    description: 'Download Skia Binary Artifacts'
    required: false
    default: 'true'
  graphite:
    description: 'Use Graphite Skia Build'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version-file: .nvmrc
        cache: yarn
        cache-dependency-path: yarn.lock

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
      env:
        SK_GRAPHITE: ${{ inputs.graphite == 'true' && '1' || '' }}

    - name: Download Skia Binary Artifacts
      if: ${{ inputs.download_skia == 'true' }}
      uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e # v2.28.0
      with:
        workflow: ${{ inputs.graphite == 'true' && 'build-skia-graphite.yml' || 'build-skia.yml' }}
        repo: shopify/react-native-skia
        path: packages/skia/artifacts
        branch: main

    - name: Copy Skia Headers
      if: ${{ inputs.download_skia == 'true' }}
      working-directory: packages/skia
      run: yarn copy-skia-headers
      shell: bash

    - name: Copy Artifacts to libs folder
      if: ${{ inputs.download_skia == 'true' }}
      working-directory: packages/skia
      run: yarn workflow-copy-libs
      shell: bash
      env:
        SK_GRAPHITE: ${{ inputs.graphite == 'true' && '1' || '' }}

    - name: Clean up artifacts folder
      if: ${{ inputs.download_skia == 'true' }}
      working-directory: packages/skia
      run: rm -rf artifacts
      shell: bash
