name: Setup
description: Setup Node.js and install dependencies

inputs:
  github_token:
    description: 'GitHub Token'
    required: false
  download_skia:
    description: 'Download Skia Binary Artifacts'
    required: false
    default: 'true'
  graphite:
    description: 'Use Graphite Skia Build'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version-file: .nvmrc
        cache: yarn
        cache-dependency-path: yarn.lock
        registry-url: 'https://registry.npmjs.org'

    - name: Upgrade npm
      run: npm install -g npm@latest
      shell: bash

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
      env:
        SK_GRAPHITE: ${{ inputs.graphite == 'true' && '1' || '' }}
        SKIP_SKIA_DOWNLOAD: ${{ inputs.download_skia == 'false' && '1' || '' }}
    
    - name: Copy Skia headers
      working-directory: packages/skia
      run: yarn copy-skia-headers
      shell: bash
