name: Setup
description: Setup Node.js and install dependencies

inputs:
  github_token:
    description: 'GitHub Token'
    required: false
  download_skia:
    description: 'Download Skia Binary Artifacts'
    required: false
    default: 'true'
  graphite:
    description: 'Use Graphite Skia Build'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    # - name: Setup Xcode 16
    #   if: runner.os == 'macOS'
    #   uses: maxim-lobanov/setup-xcode@v1
    #   with:
    #     xcode-version: '16.2.0'

    - name: Setup Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version-file: .nvmrc
        cache: yarn
        cache-dependency-path: yarn.lock

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
      env:
        SK_GRAPHITE: ${{ inputs.graphite == 'true' && '1' || '' }}

    - name: Copy Artifacts to libs folder
      if: ${{ inputs.download_skia == 'true' }}
      working-directory: packages/skia
      run: yarn install-skia --no-headers
      shell: bash
      env:
        SK_GRAPHITE: ${{ inputs.graphite == 'true' && '1' || '' }}
