export const Skia: {
    Point: (x: any, y: any) => import("./web/JsiSkPoint").JsiSkPoint;
    RuntimeShaderBuilder: (_: any) => jest.Mock<any, any, any>;
    RRectXY: (rect: any, rx: any, ry: any) => import("./web/JsiSkRRect").JsiSkRRect;
    RSXform: (scos: any, ssin: any, tx: any, ty: any) => import("./web/JsiSkRSXform").JsiSkRSXform;
    RSXformFromRadians: (scale: any, r: any, tx: any, ty: any, px: any, py: any) => import("./web/JsiSkRSXform").JsiSkRSXform;
    Color: (color: any) => Float32Array<ArrayBufferLike>;
    ContourMeasureIter: (path: any, forceClosed: any, resScale: any) => import("./web/JsiSkContourMeasureIter").JsiSkContourMeasureIter;
    Paint: () => import("./web/JsiSkPaint").JsiSkPaint;
    PictureRecorder: () => import("./web/JsiSkPictureRecorder").JsiSkPictureRecorder;
    Picture: import("./web/JsiSkPictureFactory").JsiSkPictureFactory;
    Path: import("./web/JsiSkPathFactory").JsiSkPathFactory;
    Matrix: (matrix: any) => import("./web/JsiSkMatrix").JsiSkMatrix;
    ColorFilter: import("./web/JsiSkColorFilterFactory").JsiSkColorFilterFactory;
    Font: (typeface: any, size: any) => import("./web/JsiSkFont").JsiSkFont;
    Typeface: import("./web/JsiSkTypefaceFactory").JsiSkTypefaceFactory;
    MaskFilter: import("./web/JsiSkMaskFilterFactory").JsiSkMaskFilterFactory;
    RuntimeEffect: import("./web/JsiSkRuntimeEffectFactory").JsiSkRuntimeEffectFactory;
    ImageFilter: import("./web/JsiSkImageFilterFactory").JsiSkImageFilterFactory;
    Shader: import("./web/JsiSkShaderFactory").JsiSkShaderFactory;
    PathEffect: import("./web/JsiSkPathEffectFactory").JsiSkPathEffectFactory;
    MakeVertices: (mode?: any, positions?: any, textureCoordinates?: any, colors?: any, indices?: any, isVolatile?: any) => import("./web/JsiSkVertices").JsiSkVertices;
    Data: import("./web/JsiSkDataFactory").JsiSkDataFactory;
    Image: import("./web/JsiSkImageFactory").JsiSkImageFactory;
    AnimatedImage: import("./web/JsiSkAnimatedImageFactory").JsiSkAnimatedImageFactory;
    SVG: import("./web/JsiSkSVGFactory").JsiSkSVGFactory;
    TextBlob: import("./web/JsiSkTextBlobFactory").JsiSkTextBlobFactory;
    XYWHRect: (x: any, y: any, width: any, height: any) => import("./web/JsiSkRect").JsiSkRect;
    Surface: import("./web/JsiSkSurfaceFactory").JsiSkSurfaceFactory;
    TypefaceFontProvider: import("./web/JsiSkTypefaceFontProviderFactory").JsiSkTypefaceFontProviderFactory;
    FontMgr: import("./web/JsiSkFontMgrFactory").JsiSkFontMgrFactory;
    ParagraphBuilder: import("./web/JsiSkParagraphBuilderFactory").JsiSkParagraphBuilderFactory;
    NativeBuffer: import("./web/JsiSkNativeBufferFactory").JsiSkNativeBufferFactory;
    Video: (url?: any) => Promise<any>;
    Context: (_surface: any, _width: any, _height: any) => jest.Mock<any, any, any>;
    Recorder: () => jest.Mock<any, any, any>;
};
