import { createMDX } from "fumadocs-mdx/next";
import type { NextConfig } from "next";

import { basePath } from "./src/lib/base-path";

const withMDX = createMDX();

const config: NextConfig = {
  output: "export",
  basePath,
  // Emit docs/foo/index.html (instead of docs/foo.html) so that the URLs
  // generated by the previous Docusaurus site keep working on GitHub Pages.
  trailingSlash: true,
  images: { unoptimized: true },
  // The web SkiaPictureView doesn't survive StrictMode's simulated
  // unmount/remount of layout effects in development (it redraws a picture
  // that was already disposed). Production builds are not affected.
  reactStrictMode: false,
  // The live examples run the Skia sources directly (CanvasKit on the web).
  transpilePackages: [
    "@shopify/react-native-skia",
    "react-native-web",
    "react-native-reanimated",
    "react-native-worklets",
  ],
  turbopack: {
    rules: {
      // TypeGPU compiles "use gpu" callbacks (the Redraw scene on the home
      // page) to WGSL at build time.
      "*.ts": {
        condition: {
          all: [{ not: "foreign" }, { content: /["']use gpu["']/ }],
        },
        loaders: [
          {
            loader: "babel-loader",
            options: {
              babelrc: false,
              configFile: false,
              presets: ["@babel/preset-typescript"],
              plugins: ["unplugin-typegpu/babel"],
            },
          },
        ],
      },
    },
    resolveAlias: {
      "react-native": "./src/lib/react-native.ts",
      "fs": { browser: "./src/lib/empty.ts" },
      "path": { browser: "./src/lib/empty.ts" },
      "@shopify/react-native-skia": "./src/lib/react-native-skia.ts",
    },
    resolveExtensions: [".web.tsx", ".web.ts", ".web.js", ".tsx", ".ts", ".js"],
  },
};

export default withMDX(config);
