name: Setup Android Emulator
description: Run Android emulator tests using reactivecircus/android-emulator-runner

inputs:
  api_level:
    description: 'Android API level'
    required: false
    default: '30'
  profile:
    description: 'Android device profile'
    required: false
    default: 'Nexus 5X'
  script:
    description: 'Script to run inside the emulator'
    required: true

runs:
  using: composite
  steps:
    - name: Run tests on Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.api_level }}
        target: default
        arch: arm64-v8a
        profile: ${{ inputs.profile }}
        script: ${{ inputs.script }}
