export type Routes = {
  Images: undefined;
  List: undefined;
  Shapes: undefined;
  PathEffect: undefined;
  Path: undefined;
  Clipping: undefined;
  Transform: undefined;
  ColorFilter: undefined;
  ImageFilters: undefined;
  Gradients: undefined;
  SVG: undefined;
  Touch: undefined;
  BlendModes: undefined;
  Data: undefined;
  Picture: undefined;
  Freeze: undefined;
  UseCanvas: undefined;
  Reanimated: undefined;
};
