import type { Routes } from "./Routes";

// URL path (under /api) for each screen of the API stack.
// Used by the react-navigation linking config in App.tsx and by the
// Playwright web smoke tests (e2e/web.spec.ts).
export const apiScreenPaths: Record<keyof Routes, string> = {
  List: "",
  Shapes: "shapes",
  Images: "images",
  Skottie: "skottie",
  AnimatedImages: "animated-images",
  ImageLoading: "image-loading",
  Paragraphs: "paragraphs",
  Paragraphs2: "paragraphs2",
  Clipping: "clipping",
  Touch: "touch",
  Snapshot: "snapshot",
  PathEffect: "path-effect",
  IconsExample: "icons",
  Transform: "transform",
  ZIndex: "z-index",
  ColorFilter: "color-filter",
  ImageFilters: "image-filters",
  Gradients: "gradients",
  Path: "path",
  SVG: "svg",
  BlendModes: "blend-modes",
  FontMgr: "font-mgr",
  Data: "data",
  PictureView: "picture-view",
  Picture: "picture",
  Checker: "checker",
  UseCanvas: "use-canvas",
  OnLayout: "on-layout",
  OnSize: "on-size",
  StressTest: "stress-test",
  StressTest2: "stress-test2",
  StressTest3: "stress-test3",
  StressTest4: "stress-test4",
  PictureViewCrashTest: "picture-view-crash-test",
  FirstFrame: "first-frame",
  FirstFrameEmpty: "first-frame-empty",
  PictureBug: "picture-bug",
  Atlas: "atlas",
  Web: "web",
  WebLayout: "web-layout",
  WebGLContexts: "webgl-contexts",
  WebMemory: "web-memory",
};
