export type Routes = {
  Images: undefined;
  AnimatedImages: undefined;
  List: undefined;
  Shapes: undefined;
  PathEffect: undefined;
  Path: undefined;
  Clipping: undefined;
  Transform: undefined;
  ColorFilter: undefined;
  ImageFilters: undefined;
  Gradients: undefined;
  SVG: undefined;
  Touch: undefined;
  BlendModes: undefined;
  FontMgr: undefined;
  Data: undefined;
  Picture: undefined;
  Checker: undefined;
  UseCanvas: undefined;
  PictureView: undefined;
  OnLayout: undefined;
  Snapshot: undefined;
  IconsExample: undefined;
  Paragraphs: undefined;
  Paragraphs2: undefined;
  Skottie: undefined;
};
