name: Test Latest Skia Release on iOS and Android

on:
  workflow_dispatch:
    inputs:
      skia_version:
        description: 'Skia version to test (version number, "latest", URL to .tgz, or "artifact:RUN_ID")'
        required: false
        default: 'latest'
        type: string
      simulator_device:
        description: 'iOS Simulator device'
        required: false
        default: 'iPhone 16 Pro'
        type: string
      android_api_level:
        description: 'Android API level'
        required: false
        default: '30'
        type: string
      android_device:
        description: 'Android device profile'
        required: false
        default: 'Nexus 5X'
        type: string
      test_ios:
        description: 'Run iOS tests'
        required: false
        default: true
        type: boolean
      test_android:
        description: 'Run Android tests'
        required: false
        default: true
        type: boolean
      test_web:
        description: 'Run Web tests'
        required: false
        default: true
        type: boolean

jobs:
  test-skia:
    uses: ./.github/workflows/test-skia-package.yml
    with:
      skia_version: ${{ inputs.skia_version }}
      test_ios: ${{ inputs.test_ios }}
      test_android: ${{ inputs.test_android }}
      test_web: ${{ inputs.test_web }}
      simulator_device: ${{ inputs.simulator_device }}
      android_api_level: ${{ inputs.android_api_level }}
      android_device: ${{ inputs.android_device }}
